import torch
from chronos import BaseChronosPipeline
from tools.stock_data import get_stock_history
from langchain_core.tools import tool

# Global pipeline variable for lazy loading
_pipeline = None


def _get_pipeline():
    """
    Lazy-load the Amazon Chronos T5 Tiny forecasting pipeline.
    """
    global _pipeline
    
    if _pipeline is None:
        print("  [Forecasting] Loading Chronos T5 Tiny model on CPU...")
        
        # We explicitly force "cpu" because AMD GPUs are not supported by PyTorch CUDA,
        # and this ensures we stay well within the 3.42GB usable RAM limit.
        _pipeline = BaseChronosPipeline.from_pretrained(
            "amazon/chronos-t5-tiny",
            device_map="cpu"
        )
        
    return _pipeline


def predict_stock_prices(symbol: str, exchange: str = "NSE", horizon_days: int = 10) -> dict:
    """
    Forecast the next N closing prices for a stock using Amazon Chronos.
    """
    try:
        # 1. Fetch 3 months of historical daily data
        history = get_stock_history(symbol, exchange, period="3mo", interval="1d")
        
        if "error" in history:
            return history
            
        closes = history["close"]
        historical_dates = history["dates"]
        
        # 2. Prepare the data: The new API accepts a simple 1D tensor
        context = torch.tensor(closes, dtype=torch.float32)
        
        # 3. Load the model
        pipeline = _get_pipeline()
        
        # 4. Generate forecasts using the new predict_quantiles method
        # NOTE: The parameter is 'inputs', not 'context' in the new API
        quantiles, mean = pipeline.predict_quantiles(
            inputs=context, 
            prediction_length=horizon_days, 
            quantile_levels=[0.1, 0.5, 0.9]
        )
        
        # 5. Extract the predictions from the PyTorch tensor and round them
        # quantiles shape is [batch_size, horizon, levels] -> [1, 10, 3]
        forecast_low = [round(x, 2) for x in quantiles[0, :, 0].tolist()]
        forecast_median = [round(x, 2) for x in quantiles[0, :, 1].tolist()]
        forecast_high = [round(x, 2) for x in quantiles[0, :, 2].tolist()]
        
        return {
            "symbol": symbol,
            "chart_type": "forecast",
            "historical_dates": historical_dates,
            "historical_closes": closes,
            "forecast_median": forecast_median,
            "forecast_low": forecast_low,
            "forecast_high": forecast_high,
            "horizon_days": horizon_days,
            "note": (
                "This forecast is generated by a statistical model using price patterns only. "
                "It does not account for news, earnings, or macro events. "
                "This is for educational purposes and not financial advice."
            )
        }
        
    except Exception as e:
        return {"error": str(e), "symbol": symbol}
